export const AppImage = {
  Logo: require('./logo.png'),
  SigninBackground: require('./signinBackground.png'),
  HomeBackground: require('./homeBackground.png'),
  FacebookIcon: require('./facebokIcon.png'),
  AppleIcon: require('./appleIcon.png'),
  GoogleIcon: require('./googleIcon.png'),
  checkFalse: require('./checkFalse.png'),
  checkTrue: require('./checkTrue.png'),
  drawerNavigationIcon: require('./drawerNavigationIcon.png'),
  headerLogo: require('./headerLogo.png'),
  notificationIcon: require('./notificationIcon.png'),
  morningMoments: require('./morningMoments.png'),
  closeIcon: require('./closeIcon.png'),
  logoutIcon: require('./logoutIcon.png'),
  profileIcon: require('./profileIcon.png'),
  settingIcon: require('./settingIcon.png'),
  notificationImage: require('./notificationImage.png'),
  notificationProfileIcon: require('./notificationProfileIcon.png'),
  arrowIcon: require('./arrow.png'),
  dashboardRecommendation: require('./dashboardRecommendation.png'),
  sliderImage01: require('./sliderImage01.png'),
  sliderImage02: require('./sliderImage02.png'),
  sliderImage03: require('./sliderImage03.png'),
  back: require('./back.png'),
  next: require('./next.png'),
};
